substitutions:
  _IMAGE_NAME: 'gcr.io/oppo-gcp-prod-digfood-129869/qpon-dataflow-mysql_image'
  _TAG: 'rm'  # 设置全局变量 TAG
  _PROJECT: 'oppo-gcp-prod-digfood-129869'
  _LOCATION: 'us'
  _REPOSITORY: 'gcr.io'

steps:
  # 删除同名镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['rmi', '-f', '${_IMAGE_NAME}']  # 删除之前的镜像

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts docker images delete ${_LOCATION}-docker.pkg.dev/${_PROJECT}/${_REPOSITORY}/${_IMAGE_NAME} --delete-tags --quiet || echo "No images to delete"

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}:${_TAG}', '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:${_TAG}']

  # Dataflow Flex Template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'dataflow', 'flex-template', 'build',
      'gs://qpon-dataflow-mysql/templates/pubsub-CloudSQL-template.json',
      '--image-gcr-path', '${_IMAGE_NAME}:${_TAG}',
      '--flex-template-base-image', 'PYTHON3',
      '--py-path', '.',
      '--sdk-language', 'PYTHON',
      '--env', 'FLEX_TEMPLATE_PYTHON_PY_FILE=mysqldataflowcloudsql.py',
      '--env', 'FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=requirements.txt'
    ]

timeout: 600s  # 超时时间
logsBucket: 'gs://qpon-dataflow-mysql'