steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/qpon-1c174/xhy_image:lates', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/qpon-1c174/xhy_image:lates']

  # Entrypoint, timeout and environment variables
  # Dataflow Flex Template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'dataflow', 'flex-template', 'build',
      'gs://xhy_bucket/templates/pubsub-CloudSQL-template.json',  # 替换为您的 Cloud Storage 路径
      '--image-gcr-path', 'gcr.io/qpon-1c174/xhy_image:latest', 
      '--flex-template-base-image','PYTHON3',  #必须有
      '--py-path','.',  #必须有
      '--sdk-language', 'PYTHON',
      '--env', 'FLEX_TEMPLATE_PYTHON_PY_FILE=dataflow_pipeline.py',
      '--env', 'FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=requirements.txt'
    ]

timeout: 600s  # 超时时间可以根据需要调整      
logsBucket: 'gs://xhy_bucket'

# [END cloudbuild_basic_config]

