substitutions:
  _IMAGE_NAME: 'gcr.io/oppo-gcp-prod-digfood-129869/qpon-dataflow-mysql_image'
  _TAG: 'latest'  # 设置全局变量 TAG

steps:
  # 删除同名镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['rmi', '-f', '${_IMAGE_NAME}:${_TAG}']  # 删除之前的镜像

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}:${_TAG}', '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:${_TAG}']

  # Dataflow Flex Template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'dataflow', 'flex-template', 'build',
      'gs://qpon-dataflow-mysql/templates/pubsub-CloudSQL-template.json',
      '--image-gcr-path', '${_IMAGE_NAME}:${_TAG}',
      '--flex-template-base-image', 'PYTHON3',
      '--py-path', '.',
      '--sdk-language', 'PYTHON',
      '--env', 'FLEX_TEMPLATE_PYTHON_PY_FILE=mysqldataflowcloudsql.py',
      '--env', 'FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=requirements.txt'
    ]

timeout: 600s  # 超时时间
logsBucket: 'gs://qpon-dataflow-mysql'